# Generated by Django 5.2.16 on 2026-07-09 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_identifier', models.CharField(blank=True, default='', max_length=64)),
                ('event_type', models.CharField(max_length=64)),
                ('source', models.CharField(choices=[('ai_service', 'AI Service')], default='ai_service', max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='info', max_length=32)),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('closed', 'Closed')], default='new', max_length=32)),
                ('occurred_at', models.DateTimeField()),
                ('frame_id', models.CharField(blank=True, default='', max_length=128)),
                ('track_id', models.CharField(blank=True, default='', max_length=128)),
                ('bbox', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('snapshot_path', models.CharField(blank=True, default='', max_length=512)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='cameras.camera')),
            ],
            options={
                'db_table': 'event',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
    ]
