# Generated by Django 6.0.6 on 2026-07-08 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_vector', models.JSONField(verbose_name='人脸特征向量')),
                ('image_path', models.CharField(blank=True, default='', max_length=255, verbose_name='原始图片路径')),
                ('face_type', models.CharField(choices=[('front', '正面'), ('left', '左侧'), ('right', '右侧')], max_length=32, verbose_name='人脸角度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_features', to='employees.employee', verbose_name='关联员工')),
            ],
            options={
                'db_table': 'face_feature',
                'ordering': ['employee', 'face_type'],
            },
        ),
    ]
