# Generated by Django 6.0.6 on 2026-07-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(max_length=64, unique=True, verbose_name='工号')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('department', models.CharField(blank=True, default='', max_length=128, verbose_name='部门')),
                ('position', models.CharField(blank=True, default='', max_length=128, verbose_name='岗位')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='手机号')),
                ('status', models.CharField(choices=[('active', '在职'), ('inactive', '停用')], default='active', max_length=32, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'employee',
                'ordering': ['-created_at'],
            },
        ),
    ]
