# Generated by Django 6.0.6 on 2026-07-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(unique=True, verbose_name='日报日期')),
                ('period_start', models.DateTimeField(verbose_name='统计开始时间')),
                ('period_end', models.DateTimeField(verbose_name='统计结束时间')),
                ('alert_count', models.PositiveIntegerField(default=0, verbose_name='告警总数')),
                ('high_alert_count', models.PositiveIntegerField(default=0, verbose_name='高危告警数')),
                ('pending_alert_count', models.PositiveIntegerField(default=0, verbose_name='待处理告警数')),
                ('ai_summary', models.TextField(blank=True, default='', verbose_name='AI 摘要')),
                ('content', models.TextField(blank=True, default='', verbose_name='日报正文')),
                ('document_path', models.CharField(blank=True, default='', max_length=512, verbose_name='文档相对路径')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('generated', 'Generated'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('error_message', models.TextField(blank=True, default='', verbose_name='生成错误')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='生成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'monitor_report',
                'ordering': ['-report_date'],
            },
        ),
    ]
