# Generated by Django 6.0.6 on 2026-07-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitorreport',
            options={'ordering': ['-period_start', '-id']},
        ),
        migrations.AddField(
            model_name='monitorreport',
            name='period_label',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='统计时段'),
        ),
        migrations.AlterField(
            model_name='monitorreport',
            name='report_date',
            field=models.DateField(verbose_name='日报日期'),
        ),
        migrations.AddConstraint(
            model_name='monitorreport',
            constraint=models.UniqueConstraint(fields=('period_start', 'period_end'), name='uniq_monitor_report_period'),
        ),
    ]
